# threads defaults to 5
# colors defaults to true
# followSymlinks defaults to false
# isFork defaults to false
# upstreamName defaults to 'upstream'
# Configuration example:

threads: 10
colors: false
followSymlinks: true
ignore:
  - .DS_Store
  - /repos/ignoreme
repos:
  - path: ~/repos/singlerepo
  - path: ~/mycode/singlefork
    isFork: true
  - path: /opt/anotherfork
    isFork: true
    upstreamName: mysource
  - path: ~/repos/myorg/*
  - path: ~/repos/myforks/*
    isFork: true
